//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValdemoroEn1.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ValdemoroEn1.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acerca de.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al registrarte o iniciar sesión, aceptas los .
        /// </summary>
        public static string AcceptTerms {
            get {
                return ResourceManager.GetString("AcceptTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bueno.
        /// </summary>
        public static string AirGood {
            get {
                return ResourceManager.GetString("AirGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderado.
        /// </summary>
        public static string AirMod {
            get {
                return ResourceManager.GetString("AirMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perjudicial.
        /// </summary>
        public static string AirUnhealthy {
            get {
                return ResourceManager.GetString("AirUnhealthy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perjudicial para grupos sensibles.
        /// </summary>
        public static string AirUnhealthyG {
            get {
                return ResourceManager.GetString("AirUnhealthyG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y la .
        /// </summary>
        public static string AndThe {
            get {
                return ResourceManager.GetString("AndThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aquí tu mensaje.
        /// </summary>
        public static string BodyEmail {
            get {
                return ResourceManager.GetString("BodyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autobuses.
        /// </summary>
        public static string Bus {
            get {
                return ResourceManager.GetString("Bus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartelera de cine.
        /// </summary>
        public static string CinemaListings {
            get {
                return ResourceManager.GetString("CinemaListings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parece que hay problemas con tu conexión a internet, inténtelo de nuevo más tarde..
        /// </summary>
        public static string ConexError {
            get {
                return ResourceManager.GetString("ConexError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para cualquier asunto, contactar por correo electrónico..
        /// </summary>
        public static string ContactInfo {
            get {
                return ResourceManager.GetString("ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parece que hay un error en el servidor del consorcio regional de transportes de madrid, inténtelo de nuevo más tarde..
        /// </summary>
        public static string CrtmError {
            get {
                return ResourceManager.GetString("CrtmError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceso a los horarios del transporte público. Se trata de mostrar los datos de forma sencilla y contrastada con fuentes oficiales del CRTM pero de forma particular, es decir, no hay ningún vínculo con el consorcio..
        /// </summary>
        public static string CrtmInfo {
            get {
                return ResourceManager.GetString("CrtmInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar cuenta.
        /// </summary>
        public static string DelAccount {
            get {
                return ResourceManager.GetString("DelAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten en cuenta que, al borrar tu cuenta, perderás todo acceso y toda la información relacionada con ella. Esta acción no se puede deshacer. ¿Estás seguro de que deseas proceder con la eliminación de tu cuenta?.
        /// </summary>
        public static string DelAccountMsg {
            get {
                return ResourceManager.GetString("DelAccountMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicie sesión de nuevo y luego elimine su cuenta.
        /// </summary>
        public static string DeleteError {
            get {
                return ResourceManager.GetString("DeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo registrado, utilice otro..
        /// </summary>
        public static string EmailExists {
            get {
                return ResourceManager.GetString("EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, verifica tu correo..
        /// </summary>
        public static string EmailVerificationError {
            get {
                return ResourceManager.GetString("EmailVerificationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inglés.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Espero que disfrutes de
        ///ValdemoroEn1!.
        /// </summary>
        public static string EnjoyValdemoro {
            get {
                return ResourceManager.GetString("EnjoyValdemoro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error, inténtelo de nuevo más tarde..
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parece que hay un error en tu correo..
        /// </summary>
        public static string ErrorEmail {
            get {
                return ResourceManager.GetString("ErrorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establecimientos.
        /// </summary>
        public static string Establishments {
            get {
                return ResourceManager.GetString("Establishments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comida a domicilio.
        /// </summary>
        public static string FoodDelivery {
            get {
                return ResourceManager.GetString("FoodDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Has olvidado la contraseña?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre completo.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los precios de los combustibles y los datos de las estaciones de servicio son obtenidos en tiempo real a través del servicio de Geoportal del Ministerio para la Transición Ecológica y el Reto Demográfico..
        /// </summary>
        public static string GasInfo {
            get {
                return ResourceManager.GetString("GasInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio de la gasolina.
        /// </summary>
        public static string GasPrice {
            get {
                return ResourceManager.GetString("GasPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las imágenes aquí mostradas, títulos, textos descriptivos o números de teléfono, es información pública ofrecida por Google, ValdemoroEn1 solo se límita a mostrar los datos..
        /// </summary>
        public static string GoogleInfo {
            get {
                return ResourceManager.GetString("GoogleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Tienes ya una cuenta?.
        /// </summary>
        public static string HaveAnAccount {
            get {
                return ResourceManager.GetString("HaveAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alojamientos.
        /// </summary>
        public static string Hostels {
            get {
                return ResourceManager.GetString("Hostels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario o contraseña incorrectos..
        /// </summary>
        public static string InvalidEmailPassword {
            get {
                return ResourceManager.GetString("InvalidEmailPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tiempo y la calidad de aire se obtiene en tiempo real a través del servicio que ofrece IQAir..
        /// </summary>
        public static string IQAirInfo {
            get {
                return ResourceManager.GetString("IQAirInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Únete a
        ///ValdemoroEn1!.
        /// </summary>
        public static string JoinValdemoro {
            get {
                return ResourceManager.GetString("JoinValdemoro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicia sesión.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar sesión.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Seguro que quiere cerrar sesión?.
        /// </summary>
        public static string LogoutMsg {
            get {
                return ResourceManager.GetString("LogoutMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cartelera de cine con la compra de sus entradas se obtiene en tiempo real a través de la web del Centro Comercial El Restón..
        /// </summary>
        public static string MoviesInfo {
            get {
                return ResourceManager.GetString("MoviesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi cuenta.
        /// </summary>
        public static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulsa aquí.
        /// </summary>
        public static string PressHere {
            get {
                return ResourceManager.GetString("PressHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to política de privacidad de Google.
        /// </summary>
        public static string PrivacyGoogle {
            get {
                return ResourceManager.GetString("PrivacyGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurantes.
        /// </summary>
        public static string Restaurants {
            get {
                return ResourceManager.GetString("Restaurants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horarios en tiempo real.
        /// </summary>
        public static string SchedulesRealTime {
            get {
                return ResourceManager.GetString("SchedulesRealTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Búsqueda - favoritos.
        /// </summary>
        public static string SearchBus {
            get {
                return ResourceManager.GetString("SearchBus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona un día.
        /// </summary>
        public static string SelectDay {
            get {
                return ResourceManager.GetString("SelectDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona la hora y compra tu entrada.
        /// </summary>
        public static string SelectHour {
            get {
                return ResourceManager.GetString("SelectHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona un idioma.
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona un combustible.
        /// </summary>
        public static string SelectProduct {
            get {
                return ResourceManager.GetString("SelectProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hemos enviado un correo a la dirección indicada, revise su bandeja de entrada o la carpeta de spam y siga las indicaciones..
        /// </summary>
        public static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar sesión con Apple.
        /// </summary>
        public static string SigninWithApple {
            get {
                return ResourceManager.GetString("SigninWithApple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar sesión con Facebook.
        /// </summary>
        public static string SigninWithFacebook {
            get {
                return ResourceManager.GetString("SigninWithFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar sesión con Google.
        /// </summary>
        public static string SigninWithGoogle {
            get {
                return ResourceManager.GetString("SigninWithGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regístrate gratis.
        /// </summary>
        public static string Signup {
            get {
                return ResourceManager.GetString("Signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        public static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código o nombre de la parada.
        /// </summary>
        public static string StopCode {
            get {
                return ResourceManager.GetString("StopCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to términos y condiciones .
        /// </summary>
        public static string TermsConditions {
            get {
                return ResourceManager.GetString("TermsConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teatro.
        /// </summary>
        public static string Theater {
            get {
                return ResourceManager.GetString("Theater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La compra de las entradas del teatro se obtiene a través de la web del ayuntamiento de Valdemoro..
        /// </summary>
        public static string TheaterInfo {
            get {
                return ResourceManager.GetString("TheaterInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver trailer.
        /// </summary>
        public static string Trailer {
            get {
                return ResourceManager.GetString("Trailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transporte.
        /// </summary>
        public static string Transport {
            get {
                return ResourceManager.GetString("Transport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intentar de nuevo.
        /// </summary>
        public static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValdemoroEn1 ha sido creado con la finalidad de ofrecer a los ciudadanos un acceso más directo a los establecimientos de Valdemoro..
        /// </summary>
        public static string ValdemoroEn1 {
            get {
                return ResourceManager.GetString("ValdemoroEn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña muy débil..
        /// </summary>
        public static string WeakPassword {
            get {
                return ResourceManager.GetString("WeakPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo y calidad del aire.
        /// </summary>
        public static string WeatherICA {
            get {
                return ResourceManager.GetString("WeatherICA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para más información en la web oficial..
        /// </summary>
        public static string WebInfo {
            get {
                return ResourceManager.GetString("WebInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin teléfono.
        /// </summary>
        public static string WithOutTlf {
            get {
                return ResourceManager.GetString("WithOutTlf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin página web.
        /// </summary>
        public static string WithOutWeb {
            get {
                return ResourceManager.GetString("WithOutWeb", resourceCulture);
            }
        }
    }
}
